# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180129_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 13, 33, 4, 995714, tzinfo=utc)),
        ),
    ]
